[package]
name = "remind4f"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.10", features = ["full"] }
serenity = "0.12"
